apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mongodb
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - port: 27017
      targetPort: 27017
  type: LoadBalancer